apiVersion: apps/v1 #  
kind: StatefulSet
metadata:
  name: {{ include "kubeonec.fullname" . }}-onec-server
  namespace: {{ .Values.Namespace }}
  labels:
    version: " {{- .Values.onec_server.image.tag }}"
spec:
  serviceName: onec-server
  selector:
    matchLabels:
      app: onec-server
  replicas: 1
  template:
    metadata:
      namespace: {{ .Values.Namespace }}
      labels:
        app: onec-server
    spec:
      containers:
      - name: onec-server
        {{- if .Values.onec_server.image.tag }}
        image: "{{ .Values.onec_server.image.repository }}:{{ .Values.onec_server.image.tag }}"
        {{- else }}
        image: "{{ .Values.onec_server.image.repository }}:latest"
        {{- end }}
        ports:
          - name: clmen
            containerPort: {{ .Values.clusterManagerPort }}
            protocol: TCP
          {{- range untilStep (int .Values.workProccesStartPort) (int .Values.workProccesEndPort) 1 }}  
          - name: "wp-{{ . }}"
            containerPort: {{ . }}
            protocol: TCP
          {{- end }}
      - name: ras
        image: "{{ .Values.ones_ras.image.repository}}:{{ .Values.ones_ras.image.tag}}"
        command: [ "/opt/1C/v8.3/x86_64/ras", "cluster" ]
      {{- if .Values.serviceAccount.create}}
      serviceAccount: {{ include "kubeonec.fullname" . }}-sa
      {{- end}}

